USE comandabd;

-- CATEGORÍAS: OK
CREATE TABLE `CATEGORIAS` (
  `CATEGO_ID` int NOT NULL AUTO_INCREMENT,
  `CATEGO_NOMBRE` varchar(255) NOT NULL,
  -- `CATEGO_DESCRP` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CATEGO_ID`),
  UNIQUE KEY (`CATEGO_NOMBRE`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- PRODCUTOS: OK, VUELVO A PONER PRECIO
CREATE TABLE `PRODUCTOS` (
  `PRODUC_ID` int NOT NULL AUTO_INCREMENT,
  `PRODUC_NOMBRE` varchar(255) NOT NULL,
  `PRODUC_DESCRP` varchar(255) DEFAULT NULL,
  `PRODUC_PRECIO` double NOT NULL,
  `PRODUC_CATEGO` int NOT NULL,
  -- `PRODUC_ETIQUE` int NOT NULL,
  PRIMARY KEY (`PRODUC_ID`),
  UNIQUE KEY (`PRODUC_NOMBRE`),
  KEY `FK_PRODUC_CATEGO_ID` (`PRODUC_CATEGO`),
  -- KEY `FK_PRODUC_ETIQUE_ID` (`PRODUC_ETIQUE`),
  CONSTRAINT `FK_PRODUC_CATEGO` FOREIGN KEY (`PRODUC_CATEGO`) REFERENCES `CATEGORIAS` (`CATEGO_ID`)
  -- CONSTRAINT `FK_PRODUC_ETIQUE` FOREIGN KEY (`PRODUC_ETIQUE`) REFERENCES `ETIQUETAS` (`ETIQUE_ID`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- ESTADOS: OK, VAMOS A USAR ESTA PARA ESTADO DE MESA Y ESTADO DE PEDIDOS TODO UNIFICADO?
CREATE TABLE `ESTADOS` (
  `ESTADO_ID` int NOT NULL AUTO_INCREMENT,
  `ESTADO_NOMBRE` varchar(255) NOT NULL,
  `ESTADO_DESCRP` varchar(255) NOT NULL,
  PRIMARY KEY (`ESTADO_ID`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- COMANDAS: saco MENU y RESERVA, cambio mesa x mesauso
CREATE TABLE `COMANDAS` (
  `COMAND_ID` int NOT NULL AUTO_INCREMENT,
  -- `COMAND_RESERV` int NOT NULL,
  -- `COMAND_MESA` int NOT NULL,
  -- `COMAND_MENU` int NOT NULL,
  `COMAND_ESTADO` int NOT NULL,
  PRIMARY KEY (`COMAND_ID`),
  -- KEY `FK_COMAND_RESERV` (`COMAND_RESERV`),
  -- KEY `FK_COMAND_MESA` (`COMAND_MESA`),
  -- KEY `FK_COMAND_MENU` (`COMAND_MENU`),
  KEY `FK_COMAND_ESTADO` (`COMAND_ESTADO`),
  -- CONSTRAINT `FK_COMAND_RESERV` FOREIGN KEY (`COMAND_RESERV`) REFERENCES `RESERVAS` (`RESERV_ID`),
  -- CONSTRAINT `FK_COMAND_MESA` FOREIGN KEY (`COMAND_MESA`) REFERENCES `MESAS` (`MESA_ID`),
  -- CONSTRAINT `FK_COMAND_MENU` FOREIGN KEY (`COMAND_MENU`) REFERENCES `MENU` (`MENU_ID`),
  CONSTRAINT `FK_COMAND_ESTADO` FOREIGN KEY (`COMAND_ESTADO`) REFERENCES `ESTADOS` (`ESTADO_ID`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- ITEMCOMANDAS: 
CREATE TABLE `ITEMCOMANDAS` (
  `ITEMCOM_ID` int NOT NULL AUTO_INCREMENT,
  `ITEMCOM_COMANDA` int NOT NULL,
  `ITEMCOM_PRODUC` int NOT NULL,
  `ITEMCOM_TOTAL` double DEFAULT NULL,  
  PRIMARY KEY (`ITEMCOM_ID`),
  KEY `FK_ITEMCOM_COMANDA` (`ITEMCOM_COMANDA`),
  KEY `FK_ITEMCOM_PRODUC` (`ITEMCOM_PRODUC`),
  -- KEY `FK_COMITS_ESTADO` (`COMITS_ESTADO`),
  CONSTRAINT `FK_ITEMCOM_COMANDA` FOREIGN KEY (`ITEMCOM_COMANDA`) REFERENCES `COMANDAS` (`COMAND_ID`),
  CONSTRAINT `FK_ITEMCOM_PRODUC` FOREIGN KEY (`ITEMCOM_PRODUC`) REFERENCES `PRODUCTOS` (`PRODUC_ID`)
  -- CONSTRAINT `FK_COMITS_ESTADO` FOREIGN KEY (`COMITS_ESTADO`) REFERENCES `ESTADOS` (`ESTADO_ID`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

